#!/usr/bin/env python3
"""Render a shortlist JSON (the source of truth) to a static HTML page.

Usage: python3 -B build_shortlist.py <shortlist.json> <out.html>

Stdlib only, Python 3.10+. The HTML is generated from
``assets/shortlist.template.html`` and works offline: all data is embedded,
there are no CDNs or network calls. Schema, status vocabulary, and the default
behavior live in ``references/shortlists.md``.
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
TEMPLATE = SKILL_DIR / "assets" / "shortlist.template.html"

STATUSES = ("candidate", "shortlisted", "contacted", "chosen", "rejected")
DEFAULT_STATUS = "candidate"
PLACEHOLDER = re.compile(r"\{\{[A-Z_0-9]+\}\}")


class ShortlistError(ValueError):
    """The shortlist JSON is malformed or fails schema validation."""


def _check(condition: object, message: str) -> None:
    if not condition:
        raise ShortlistError(message)


def _nonempty_str(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def validate(data: object) -> dict:
    """Validate a parsed shortlist; return it unchanged or raise ShortlistError."""
    _check(isinstance(data, dict), "shortlist: must be a JSON object")
    assert isinstance(data, dict)
    _check(_nonempty_str(data.get("title")), "title: required non-empty string")
    criteria = data.get("criteria")
    _check(
        isinstance(criteria, list) and criteria and all(_nonempty_str(c) for c in criteria),
        "criteria: required non-empty array of strings",
    )
    columns = data.get("columns")
    _check(columns is None or isinstance(columns, list), "columns: must be an array when present")
    items = data.get("items")
    _check(isinstance(items, list) and items, "items: required non-empty array")
    assert isinstance(items, list)
    seen: set[str] = set()
    for index, item in enumerate(items):
        where = f"items[{index}]"
        _check(isinstance(item, dict), f"{where}: must be an object")
        assert isinstance(item, dict)
        _check(_nonempty_str(item.get("id")), f"{where}.id: required non-empty string")
        _check(_nonempty_str(item.get("name")), f"{where}.name: required non-empty string")
        _check(item["id"] not in seen, f"{where}.id: duplicate id {item['id']!r}")
        seen.add(item["id"])
        status = item.get("status", DEFAULT_STATUS)
        _check(
            status in STATUSES,
            f"{where}.status: {status!r} is not one of {', '.join(STATUSES)}",
        )
        if status == "rejected":
            _check(
                _nonempty_str(item.get("rejectedReason")),
                f"{where}.rejectedReason: required when status is 'rejected'",
            )
        for field in ("tags", "evidence", "risks"):
            value = item.get(field)
            _check(value is None or isinstance(value, list), f"{where}.{field}: must be an array")
    return data


def embed_json(data: dict) -> str:
    """JSON with ``<`` escaped so it cannot break out of a <script> block."""
    text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return text.replace("<", "\\u003c")


def escape(value: object) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def render(data: dict, source: str) -> str:
    lane = data.get("lane") or "shortlist"
    context = data.get("trip") or ""
    generated = str(data.get("generatedAt") or "")
    badge = lane + (f" · {context}" if context and context != "none" else "")
    if generated:
        badge += f" · built {generated}"
    footer = f"Generated by build_shortlist.py from {source}"
    if generated:
        footer += f" · {generated}"
    fields = {
        "TITLE": escape(data.get("title", "")),
        "SUBTITLE": escape(data.get("subtitle", "")),
        "BADGE": escape(badge),
        "FOOTER": escape(footer),
        "SHORTLIST_JSON": embed_json(data),
    }
    page = TEMPLATE.read_text(encoding="utf-8")
    for key, value in fields.items():
        page = page.replace("{{" + key + "}}", value)
    leftover = sorted(set(PLACEHOLDER.findall(page)))
    _check(not leftover, "unfilled template placeholders: " + ", ".join(leftover))
    return page


def build(in_path: str | Path, out_path: str | Path) -> int:
    """Validate ``in_path`` and write the generated page to ``out_path``."""
    try:
        raw = Path(in_path).read_text(encoding="utf-8")
    except OSError as error:
        raise ShortlistError(f"{in_path}: cannot read: {error}") from error
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as error:
        raise ShortlistError(f"{in_path}: invalid JSON: {error}") from error
    validate(data)
    Path(out_path).write_text(render(data, str(in_path)), encoding="utf-8")
    return len(data["items"])


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: build_shortlist.py <shortlist.json> <out.html>", file=sys.stderr)
        return 2
    try:
        count = build(argv[1], argv[2])
    except ShortlistError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"wrote {argv[2]} ({count} items)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
